import { drizzle } from "drizzle-orm/mysql2";
import { trips } from "./drizzle/schema.ts";

const db = drizzle(process.env.DATABASE_URL);

const sampleTrips = [
  {
    userId: 1,
    title: "Rheinfall Schaffhausen",
    description: "Besuche Europas größten Wasserfall! Ein beeindruckendes Naturschauspiel mit Bootsfahrten und Aussichtsplattformen.",
    destination: "Schaffhausen",
    region: "Zürich",
    category: "Hiking",
    cost: "low",
    ageRecommendation: "Alle Altersgruppen",
    routeType: "location",
    websiteUrl: "https://www.rheinfall.ch",
    contactEmail: "info@rheinfall.ch",
    startDate: new Date("2024-06-15"),
    endDate: new Date("2024-06-15"),
    participants: 4,
    status: "planned",
    isPublic: 1,
    isFavorite: 1,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Aquaparc Le Bouveret",
    description: "Der größte Wasserpark der Schweiz! Über 10 Rutschen, Wellenbad und Spa-Bereich für die ganze Familie.",
    destination: "Le Bouveret",
    region: "Tessin",
    category: "Water park",
    cost: "high",
    ageRecommendation: "Ab 3 Jahren",
    routeType: "location",
    websiteUrl: "https://www.aquaparc.ch",
    contactEmail: "+41 24 481 61 00",
    startDate: new Date("2024-07-20"),
    endDate: new Date("2024-07-20"),
    participants: 5,
    status: "planned",
    isPublic: 1,
    isFavorite: 0,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Pilatus Seilbahn",
    description: "Fahrt mit der steilsten Zahnradbahn der Welt auf den Pilatus. Atemberaubende Aussicht auf die Alpen!",
    destination: "Alpnachstad",
    region: "Luzern",
    category: "Action",
    cost: "very_high",
    ageRecommendation: "Ab 5 Jahren",
    routeType: "one_way",
    websiteUrl: "https://www.pilatus.ch",
    contactEmail: "+41 41 329 11 11",
    startDate: new Date("2024-08-10"),
    endDate: new Date("2024-08-10"),
    participants: 3,
    status: "planned",
    isPublic: 1,
    isFavorite: 1,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Spielplatz Bärenpark Bern",
    description: "Kostenloser Abenteuerspielplatz mit Blick auf die Bären im Bärenpark. Perfekt für einen Nachmittag!",
    destination: "Bern",
    region: "Bern",
    category: "Playground",
    cost: "free",
    ageRecommendation: "2-12 Jahre",
    routeType: "location",
    websiteUrl: "https://www.baerenpark-bern.ch",
    contactEmail: "info@baerenpark-bern.ch",
    startDate: new Date("2024-05-25"),
    endDate: new Date("2024-05-25"),
    participants: 2,
    status: "completed",
    isPublic: 1,
    isFavorite: 0,
    isDone: 1,
  },
  {
    userId: 1,
    title: "Zoo Zürich",
    description: "Einer der besten Zoos Europas mit über 4000 Tieren. Highlights: Masoala-Regenwald und Elefantenpark.",
    destination: "Zürich",
    region: "Zürich",
    category: "Animal park/Zoo",
    cost: "medium",
    ageRecommendation: "Alle Altersgruppen",
    routeType: "location",
    websiteUrl: "https://www.zoo.ch",
    contactEmail: "+41 44 254 25 00",
    startDate: new Date("2024-09-05"),
    endDate: new Date("2024-09-05"),
    participants: 6,
    status: "planned",
    isPublic: 1,
    isFavorite: 1,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Foxtrail Schnitzeljagd Basel",
    description: "Spannende Schnitzeljagd durch die Altstadt von Basel. Rätsel lösen und die Stadt entdecken!",
    destination: "Basel",
    region: "Basel",
    category: "Scavenger hunt",
    cost: "medium",
    ageRecommendation: "Ab 8 Jahren",
    routeType: "round_trip",
    websiteUrl: "https://www.foxtrail.ch",
    contactEmail: "info@foxtrail.ch",
    startDate: new Date("2024-06-30"),
    endDate: new Date("2024-06-30"),
    participants: 4,
    status: "planned",
    isPublic: 1,
    isFavorite: 0,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Pumptrack Chur",
    description: "Moderner Pumptrack für Bikes, Scooter und Skateboards. Gratis und für alle Levels geeignet!",
    destination: "Chur",
    region: "Graubünden",
    category: "Pumptrack",
    cost: "free",
    ageRecommendation: "Ab 6 Jahren",
    routeType: "location",
    websiteUrl: "https://www.chur.ch",
    contactEmail: "info@chur.ch",
    startDate: new Date("2024-07-15"),
    endDate: new Date("2024-07-15"),
    participants: 3,
    status: "planned",
    isPublic: 1,
    isFavorite: 0,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Ballenberg Freilichtmuseum",
    description: "Schweizer Freilichtmuseum mit über 100 historischen Gebäuden. Tiere, Handwerk und Traditionen erleben!",
    destination: "Hofstetten bei Brienz",
    region: "Bern",
    category: "Culture",
    cost: "medium",
    ageRecommendation: "Alle Altersgruppen",
    routeType: "round_trip",
    websiteUrl: "https://www.ballenberg.ch",
    contactEmail: "+41 33 952 10 30",
    startDate: new Date("2024-08-20"),
    endDate: new Date("2024-08-20"),
    participants: 5,
    status: "planned",
    isPublic: 1,
    isFavorite: 0,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Conny-Land Freizeitpark",
    description: "Schweizer Freizeitpark mit Achterbahnen, Wasserattraktionen und Shows für die ganze Familie.",
    destination: "Lipperswil",
    region: "Zürich",
    category: "Amusement park",
    cost: "high",
    ageRecommendation: "Ab 3 Jahren",
    routeType: "location",
    websiteUrl: "https://www.connyland.ch",
    contactEmail: "+41 71 669 11 11",
    startDate: new Date("2024-07-25"),
    endDate: new Date("2024-07-25"),
    participants: 4,
    status: "planned",
    isPublic: 1,
    isFavorite: 1,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Wanderung Oeschinensee",
    description: "Traumhafte Wanderung zum türkisblauen Bergsee. UNESCO-Welterbe mit Bootsverleih und Bergrestaurant.",
    destination: "Kandersteg",
    region: "Bern",
    category: "Hiking",
    cost: "low",
    ageRecommendation: "Ab 5 Jahren",
    routeType: "round_trip",
    websiteUrl: "https://www.oeschinensee.ch",
    contactEmail: "info@oeschinensee.ch",
    startDate: new Date("2024-09-15"),
    endDate: new Date("2024-09-15"),
    participants: 4,
    status: "planned",
    isPublic: 1,
    isFavorite: 1,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Indoor Spielplatz Happyland",
    description: "Riesiger Indoor-Spielplatz mit Hüpfburgen, Kletterwand und Trampolin. Perfekt bei schlechtem Wetter!",
    destination: "Volketswil",
    region: "Zürich",
    category: "Indoor playground",
    cost: "low",
    ageRecommendation: "1-12 Jahre",
    routeType: "location",
    websiteUrl: "https://www.happyland.ch",
    contactEmail: "+41 44 945 15 15",
    startDate: new Date("2024-11-10"),
    endDate: new Date("2024-11-10"),
    participants: 3,
    status: "planned",
    isPublic: 1,
    isFavorite: 0,
    isDone: 0,
  },
  {
    userId: 1,
    title: "Restaurant Alpenrose",
    description: "Familienfreundliches Bergrestaurant mit Spielplatz und Streichelzoo. Hausgemachte Schweizer Küche.",
    destination: "Appenzell",
    region: "St. Gallen",
    category: "Restaurant",
    cost: "medium",
    ageRecommendation: "Alle Altersgruppen",
    routeType: "location",
    websiteUrl: "https://www.alpenrose-appenzell.ch",
    contactEmail: "+41 71 787 12 34",
    startDate: new Date("2024-06-20"),
    endDate: new Date("2024-06-20"),
    participants: 5,
    status: "planned",
    isPublic: 1,
    isFavorite: 0,
    isDone: 0,
  },
];

async function seedDatabase() {
  try {
    console.log("Starting to seed database with sample trips...");
    
    for (const trip of sampleTrips) {
      await db.insert(trips).values(trip);
      console.log(`✓ Added: ${trip.title}`);
    }
    
    console.log(`\n✅ Successfully added ${sampleTrips.length} sample trips!`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();
